// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbuGYMxcOonYyHXpIc8WbPsxgE2Sh7pZQ',
    appId: '1:671616887473:web:b9024f326ae2796bf81090',
    messagingSenderId: '671616887473',
    projectId: 'my-ai-assistant-e15a6',
    authDomain: 'my-ai-assistant-e15a6.firebaseapp.com',
    storageBucket: 'my-ai-assistant-e15a6.appspot.com',
    measurementId: 'G-QFR7QJ0DPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCh5BcdFrAon7osoMvNHJjQ3TbRSiqBrw',
    appId: '1:671616887473:android:0f04fa66a2218e53f81090',
    messagingSenderId: '671616887473',
    projectId: 'my-ai-assistant-e15a6',
    storageBucket: 'my-ai-assistant-e15a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnq9ZsRp9LaoFccXfZmmYBPPDh7ILpCGc',
    appId: '1:671616887473:ios:4cae39dd4f0b093ff81090',
    messagingSenderId: '671616887473',
    projectId: 'my-ai-assistant-e15a6',
    storageBucket: 'my-ai-assistant-e15a6.appspot.com',
    iosBundleId: 'com.example.myAiAssistantFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnq9ZsRp9LaoFccXfZmmYBPPDh7ILpCGc',
    appId: '1:671616887473:ios:4cae39dd4f0b093ff81090',
    messagingSenderId: '671616887473',
    projectId: 'my-ai-assistant-e15a6',
    storageBucket: 'my-ai-assistant-e15a6.appspot.com',
    iosBundleId: 'com.example.myAiAssistantFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbuGYMxcOonYyHXpIc8WbPsxgE2Sh7pZQ',
    appId: '1:671616887473:web:9a9355111ee049a1f81090',
    messagingSenderId: '671616887473',
    projectId: 'my-ai-assistant-e15a6',
    authDomain: 'my-ai-assistant-e15a6.firebaseapp.com',
    storageBucket: 'my-ai-assistant-e15a6.appspot.com',
    measurementId: 'G-R5F9G4ZEWJ',
  );
}
